#! /usr/bin/env python
# arping2tex : arpings a network and outputs a LaTeX table as a result
# Don't forget: yum -y install tcpdump
import sys
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import srp,Ether,ARP,conf

if len(sys.argv) != 2:
    print("Usage: ./arping 192.168.1.0/24")
    sys.exit(1)

conf.verb=2
ans,unans=srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst=sys.argv[1]), timeout=2)

print('')
print('Result of APRING: ')
for snd,rcv in ans:
    print(rcv.sprintf("%Ether.src% & %ARP.psrc%"))
